name: "My first Action"

on:
  push:
    branches:
      - main 
  workflow_dispatch:
  pull_request:
    types: opened
    
env:
  TEST_NAME: "From Minsk"
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output commands
        run: echo $JSON | jq
    env:
      JSON: ${{ toJSON(github.event) }}
  artifact-job-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Print file
        #working-directory: /test
        run: cat test/2.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: test
          name: Upload-Artifact
  artifact-job-dowload:
    runs-on: ubuntu-latest
    needs: artifact-job-upload
    steps:
      - name: Get artifact-upload
        uses: actions/download-artifact@v3
        with:
          name: Upload-Artifact
      - name: ls files
        run: ls -la
        
  
