name: "My first Action"

on: 
  workflow_dispatch:
env:
  TEST_NAME: "From Minsk"
jobs:
  test:
    runs-on: ubuntu
    steps:
      - name: First test
        run: "echo Hello world ${{ env.TEST_NAME }}"
        
        
  
