name: "My first Action"

on:
  workflow_dispatch:
 
    
env:
  TEST_NAME: "From Minsk"
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output commands
        run: echo $JSON | jq
    env:
      JSON: ${{ toJSON(github.event) }}

  nexus:
    runs-on: ubuntu-latest 
    steps:
      - name: copy code
        uses: actions/checkout@v3
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http:////0.tcp.eu.ngrok.io:15138
          username: karate
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: karate-repo
          coordinates: groupId=file artifactId=app version=2.0.0
          assets: extension=jar
          filename: java-app-1.0-SNAPSHOT.jar
       
