name: "My first Action"

on: 
  workflow_dispatch:
  pull_request:
    types: opened
    
env:
  TEST_NAME: "From Minsk"
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output commands
        run: echo $JSON | jq
    env:
      JSON: ${{ toJSON(github.event) }}
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Upload Arctifact
        uses: action/upload-artifact@v4
        with:
          name: file-artifact
          path: 1.txt
        
        
  
