name: "My first Action"

on:
  push:
    branches:
      - main 
  workflow_dispatch:
  pull_request:
    types: opened
    
env:
  TEST_NAME: "From Minsk"
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output commands
        run: echo $JSON | jq
    env:
      JSON: ${{ toJSON(github.event) }}
  artifact-job:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Print file
        working-directory: /test
        run: cat 2.txt


        
        
  
