name: "My first Action"

on:
  workflow_dispatch:
 
    
env:
  TEST_NAME: "From Minsk"
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output commands
        run: echo $JSON | jq
    env:
      JSON: ${{ toJSON(github.event) }}
  artifact-job-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Copy code
        uses: actions/checkout@v3
      - name: Print file
        #working-directory: /test
        run: cat test/2.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: test
          name: Upload-Artifact
  artifact-job-dowload:
    runs-on: ubuntu-latest
    needs: artifact-job-upload
    steps:
      - name: Get artifact-upload
        uses: actions/download-artifact@v3
        with:
          name: Upload-Artifact
      - name: ls files
        run: ls -la
  nexus:
    runs-on: ubuntu-latest
    needs: [test-job, artifact-job-upload, artifact-job-dowload]
    steps:
      - name: copy code
        uses: actions/checkout@v3
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http://5.tcp.eu.ngrok.io:11905
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: my-first-nexus-repo
          coordinates: groupId=com.example artifactId=app version=1.0.0
          assets: extension=jar
          filename: ./test/file.jar
       
