name: "My first Action"

on: 
  workflow_dispatch:
  pull_request:
    types: opened
  push:
    
env:
  TEST_NAME: "From Minsk"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: First test
        run: echo $JSON | jq
    env:
      JSON: ${{ toJSON(github.event) }}
        
        
  
